### ISSUE TITLE
SPEX download website changed

### ISSUE THREAD

**Issue by jdeplaa** [HEASARC/astro_update#1]
Dear Astro-update maintainers,

Some time ago, we changed the download page of our SPEX software to a new location on Github and moved the download files to Zenodo. However, I noticed that the astro-update script is looking for new releases on the old site. Although releases are announced there as well, the script appears to pick up the DOI number of the Zenodo link as SPEX version number.

Could you change the SPEX download page in the definitions to look into this page: https://spex-xray.github.io/spex-help/getstarted/install.html The most recent SPEX releases and download files can be found there.

Thanks and best wishes,

Jelle.

**Comment by mfacorcoran** [comment]
Dear Jelle, 

 

I’ve updated the Astro-update definition for SPEX to use : https://spex-xray.github.io/spex-help/getstarted/install.html as the download link and updated the search for the version number.  Please see the SPEX entry at https://heasarc.gsfc.nasa.gov/docs/heasarc/astro-update/

 

As far as I could see however there’s no easy way to determine on what date a particular version was released.  Can you point me to the release date?  Or could you add a sentence on : https://spex-xray.github.io/spex-help/getstarted/install.html saying “Version N.NN.NN was released on YYYY-MM-DD”?  that would be very helpful (Astro-update lists software by most recent release date as you know, so not finding an accurate release date for a given version makes it difficult to find the most recent release)

 

Thanks

 

Mike

 

****************************************************

Dr. Michael F. Corcoran

The Catholic University of America

Goddard Space Flight Center, Code 662

Greenbelt, MD 20771

****************************************************

 

From: Jelle de Plaa ***@***.***>
Reply-To: HEASARC/astro_update ***@***.***>
Date: Wednesday, August 3, 2022 at 3:55 AM
To: HEASARC/astro_update ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [HEASARC/astro_update] SPEX download website changed (Issue #1)

 

Dear Astro-update maintainers,

Some time ago, we changed the download page of our SPEX software to a new location on Github and moved the download files to Zenodo. However, I noticed that the astro-update script is looking for new releases on the old site. Although releases are announced there as well, the script appears to pick up the DOI number of the Zenodo link as SPEX version number.

Could you change the SPEX download page in the definitions to look into this page: https://spex-xray.github.io/spex-help/getstarted/install.html The most recent SPEX releases and download files can be found there.

Thanks and best wishes,

Jelle.

**Comment by jdeplaa** [comment]
Dear Mike,

Thanks a lot for changing this! The release date is in the Zenodo entry, but that is not very helpful for your script. I have added a line with the version and release date to https://spex-xray.github.io/spex-help/getstarted/install.html as you requested.

Thanks again and cheers,

Jelle.

**Comment by mfacorcoran** [comment]
Dear Jelle,

 

Thanks that works great – please see 

 

https://heasarc.gsfc.nasa.gov/docs/heasarc/astro-update/

 

cheers

 

Mike

 

From: Jelle de Plaa ***@***.***>
Reply-To: HEASARC/astro_update ***@***.***>
Date: Thursday, August 4, 2022 at 3:08 AM
To: HEASARC/astro_update ***@***.***>
Cc: Michael Corcoran ***@***.***>, Comment ***@***.***>
Subject: Re: [HEASARC/astro_update] SPEX download website changed (Issue #1)

 

Dear Mike,

Thanks a lot for changing this! The release date is in the Zenodo entry, but that is not very helpful for your script. I have added a line with the version and release date to https://spex-xray.github.io/spex-help/getstarted/install.html as you requested.

Thanks again and cheers,

Jelle.

**Comment by jdeplaa** [comment]
Thanks a lot! That looks great.
